ci: rework authentication
In November 2021, authentication for the az cli command started to fail:
https://github.com/NordicSemiconductor/asset-tracker-cloud-azure-js/runs/4078990706?check_suite_focus=true

> ERROR: Could not retrieve credential from local cache for service principal 6441e566-e9ef-433c-bf3e-476b339c605e. Run `az login` for this service principal.

For some reason the login no longer worked, so this switch to the
`azure/CLI@v1` action.